/// Flutter icons Water_drop
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Water_drop
///      fonts:
///       - asset: fonts/Water_drop.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Water_drop {
  Water_drop._();

  static const _kFontFam = 'Water_drop';
  static const String _kFontPkg = null;

  static const IconData water_drop_black_24dp = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
